export interface ICommonApi
{
	UserAppNameAdd(payload: any)
	getCellSize()
	saveCellSize(payload: any)
	dltCellSize(payload: any)
	getCategory()
	saveCategory(payload: any)
	dltCategory(payload: any)
	getUnitOfMeasure()
	saveUnitOfMeasure(payload: any)
	dltUnitOfMeasure(payload: any)
	SearchItem(payload: any)
	LocationEnd(payload: any)
	LocationBegin(payload: any)
	ScanCodeTypes()
	CodeTypeSave(payload: any)
	ScanCodeTypeDelete(payload: any)
	GetWarehouses()
	CategoryDelete(payload: any)
	getSearchedItem(payload: any)
	ItemExists(payload: any)
	SupplierItemIDInfo(payload: any)
	UserFieldGetByID(payload: any)
	UserFieldTypeAhead(payload: any)
	UserFieldMTSave(payload: any)
	SupplierItemTypeAhead(payload: any)
	updateAppName(payload: any)
	saveWareHouse(payload: any)
	dltWareHouse(payload: any)
	getVelocityCode(payload? : any)
	saveVelocityCode(payload: any)
	dltVelocityCode(payload: any)
	getAdjustmentReasonsList()
	getItemQuantityDetail(payload: any)
}