import { AdminApiService } from "./admin-api.service"

export interface IAdminApiService extends AdminApiService
{
    TransactionQtyReplenishmentUpdate(body);
      ReplenishmentsByDelete(body);
      DeleteRangeBegin(body);
      DeleteRangeEnd(body);
      SystemReplenishNewTA(body);
      ReplenishmentsIncludeAllUpdate(body);
      ReplenishmentsIncludeUpdate(body);
      ProcessReplenishments(body);
      ReplenishmentInsert(body);
      SystemReplenishmentNewTable(body);
      SystemReplenishmentTable(body);
      ReplenishReportSearchTA(body);
      SystemReplenishmentCount(body);
      FiltersItemNumInsert(body);
      GetLocAssPutAwayTable() ;
      LocationAssignmentOrderInsert(body);
      GetLocationAssignmentPickTable(body);
      GetTransactionTypeCounts(body);
      EventLogTable(body);
      EventLogTypeAhead(body);
      EventRangeDelete(body);
      SelectedEventDelete(body);
      DeleteKit(body);
      InsertKit(body);
      UpdateKit(body);
      GetColumnSequence(body);
      GeneralPreferenceSave(body);
      ordersort() ;
      OSFieldFilterNames();
      AdminCompanyInfo();
      ColumnAlias() ;
      FieldNameSave(body);
      RemoveccQueueRow(body);
      RemoveccQueueAll() ;
      CreateCountRecords() ;
      GetCCQueue(body);
      GetMoveItemsTable(body);
      CreateMoveTransactions(body);
      CycleCountQueueInsert(body);
      BatchResultTable(body);
      GetCountBatches();
      QuantitySelected(body);
      GetCCCountToCostTypeAhead(body);
      GetCCCategoryTypeAhead(body);
      GetCCDescriptionTypeAhead(body);
      CountOrdersDelete(body);
      UpdateReelQuantity(body);
      UpdateReelAll(body);
      RefreshRTS(body);
      UpdateScanCodes(body);
      DeleteScanCode(body);
      InsertScanCodes(body);
      RefreshScanCodes(body);
      getSearchData(body);
      duplicate(body);
      getInventoryMap(body);
      getSetColumnSeq(body);
      SelectBatchesDeleteDrop(body);
      BatchDeleteAll(body);
      PickToteIDUpdate(body);
      BatchInsert(body);
      DetailView(body);
      BatchManagerOrder(body);
      GetBatchManager(body);
      GetAdminMenu() ;
      EmployeeData() ;
      Stats(body);
      Lookup(body);
      Controlname(body);
      Groupname(body);
      Groupnames(body);
      Employee(body);
      DeleteEmployee(body);
      UpdateEmployee(body);
      EmployeeDetails(body);
      Inventorymasterdata(body);
      location(body);
      GetInventory(body);
      GetInventoryItemNumber(body);
      GetInventoryMasterData(body);
      UpdateInventoryMaster(body);
      UpdateItemNumber(body);
      AddNewItem(body);
      NextItemNumber(body);
      GetInventoryMasterLocation(body);
      DeleteItem(body);
      UpdateInventoryMasterOTQuarantine(body);
      UpdateInventoryMasterOTUnQuarantine(body);
      GetLocationTable(body);
      PreviousItemNumber(body);
      getEmployeeData(body);
      getInsertAllAccess(body);
      getUserRights(body);
      getAdminEmployeeLookup(body, isLoader);
      employeeStatsInfo(body);
      saveAdminEmployee(body);
      deleteAdminEmployee(body);
      deleteUserGroup(body); 
      updateAdminEmployee(body);
      cloneGroup(body); 
      getAdminEmployeeDetails(body); 
      getControlName(body); 
      updateControlName(body);
      deleteControlName(body); 
      submitControlResponse(body);
      insertUserGroup(body);   
      getZones() 
      updateEmployeeZone(body); 
      deleteEmployeeZone(body); 
      insertAllAccess(body);  
      insertEmployeeLocation(body); 
      updateEmployeeLocation(body);
      deleteEmployeeLocation(body); 
      insertPickLevels(body); 
      updatePickLevels(body);
      deletePickLevels(body);
      updateAccessGroup(body)
      insertGroup(body);
      insertGroupFunctions(body);
      getFunctionByGroup(body);
      updateEmployeesInGroup(body);
      deleteGroup(body);
      getItemNumDetail(body);
      getLocZTypeInvMap(body);
      updateInventoryMap(body,mapID)
       // check api call 
      createInventoryMap(body)
      GetLocAssCountTable();
      PreviewLocAssignmentPickShortFPZ();
      PreviewLocAssignmentPickShort(); 
    TransactionHistoryTable(body); 
    TransactionModelIndex(body); 
    NextSuggestedTransactions(body); 
    ReprocessTypeahead(body); 
    ReprocessedTransactionTable(body); 
    TransactionForOrderInsert(body); 
    TransactionForOrderUpdate(body);  
    ReprocessedTransactionHistoryTable(body);  
    ReprocessTransactionTable(body); 
    OrderToPost(body);  
    ReprocessIncludeSet(body); 
    
    SetAllReprocessColumn(body);  
    ReprocessTransactionData(body); 
    PostReprocessTransaction(body); 
    OrderNumberNext(body); 
    ScanValidateOrder(body); 
    DeleteOrder(body); 
    OrderStatusData(body); 
    OpenTransactionTable(body); 
    HoldTransactionsData(body);  
    UpdateTransaction(body); 
    LocationData(body); 
    PostTransaction(body); 
    ManualTransactionTypeAhead(body);  
    TransactionInfo(body); 
    TransactionDelete(body); 
    TransactionForOrderDelete(body); 
    DeallocateTransactions(body); 
    TransactionByID(body); 
    GernerateOrderTable(body); 
    ManualOrderTypeAhead(body); 
     
    NewTransactionSave(body);
    GetLocations(body);
    ManualOrdersPost(body);
    SendCompletedToTH(body);    
    GetColumnSequenceDetail(body);
    DeleteColumns(body);
    SaveColumns(body);
    AllocatedOrders(body);
    AllocatedItems(body);
    AllAllocatedOrders(body);
    OrderItemsTable(body);
    DeAllocateOrder(body) ; 
    SaveTransaction(body); 
    ReprocessTransactionDelete(body);
    deleteInventoryMap(body); 
    quarantineInventoryMap(body); 
    unQuarantineInventoryMap(body); 
    DevicePreferencesDelete(body);
    GetCartonFlow(body)
    UpdateCartonFlow(body);
    DevicePreferencesTable(body);
    LocationNamesSave(body);
    DeleteLocationNames(body);
    ZoneDevicePreferencesUpdateAll(body);
    DeviceInformation(body);
    DevicePreference(body);
    LocationZoneSave(body);
      LocationZoneDelete(body);
    LocationZoneNewSave(body);
    updateItemQuantity(body);
    LocationZone();
    LocationNames();
    adjustmentlookup();
    getToteCell();
    Getcustomreports(body)
    Getreportdetails(body); 
    selShipComp(body);   
    updateAdjustlookup(body);
    deleteAdjustmentLookup(body);
    userfieldlookup(body);
    updateuserfieldlookup(body);
    deleteUserfieldLookUp(body);
    totesetup(body);    
    deleteTote(body);
    cleartote(body)  
    basicreportdetails(body); 
    ReportFieldsExps(body); 
    reportfieldvalues(body); 
    ReportTitles(body); 
    changefilter(body);
    importFile(body); 
    validateNewDesign(body)
    getLLDesignerNewDesign(body)
    restoreDesign(body) 
    deleteReport(body) 
    pushReportChanges(body);  
    updatereportDetails(body) 
    CommonExport(body);    
    CommonPrint(body) 
    SetReprocessIds(body)
    ToteSetupInsert(body)
    ToteSetupDelete(body)
    ToteSetup();
    UpdateOSPriority(body)
    DeleteOrderStatus(body) 
}