import { ConsolidationApiService } from "./consolidation-api.service"

export interface IConsolidationApi extends ConsolidationApiService
{
	ContIDShipTransUpdate(payload: any)
	CarrierSave(payload: any)
	CarrierSelect()
	ConsolidationData(payload: any)
	StagingLocationsUpdate(payload: any)
	ConsoleDataSB(payload: any)
	ConsolidationPreferenceUpdate(payload: any)
	SystemPreferenceEmailSlip(payload: any)
	ConsolidationPreferenceShipUpdate(payload: any)
	ConsolidationIndex(payload: any)
	ShippingButtSet(payload: any)
	VerifyAllItemPost(payload: any)
	UnVerifyAll(payload: any)
	VerifyItemPost(payload: any)
	DeleteVerified(payload: any)
	ConsoleItemsTypeAhead(payload: any)
	CompleteShipment(payload: any)
	SelCountOfOpenTransactionsTemp(payload: any)
	ShipmentItemUpdate(payload: any)
	ShipmentItemDelete(payload: any)
	ShippingIndex(payload: any)
	ShippingTransactionIndex(payload: any)
	CompletePackingUpdate(payload: any)
	SplitLineTrans(payload: any)
	ShipQTYShipTransUpdate(payload: any)
	ContainerIdSingleShipTransUpdate(payload: any)
	ShippingItemAdd(payload: any)
	ItemModelData(payload: any)
	ConfPackProcModalUpdate(payload: any)
	ConfPackProcModal(payload: any)
	ConfPackSelectDT(payload: any)
	ConfirmAllConfPack(payload: any)
	ConfirmAndPackingIndex(payload: any)
	ShipTransUnPackUpdate(payload: any)
	SelContIDConfirmPack(payload: any)
	CarrierDelete(payload: any)
	viewShipping(payload: any)
	ShowCMPackPrintModal(payload: any)
}