#!/bin/sh

# Read the commit message
COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat $COMMIT_MSG_FILE)

# Define the regex pattern for your commit message
PATTERN="^\[PLM-[0-9]+\] \| .+ \| .{25,}$"

# Check if the commit message matches the pattern
if ! echo "$COMMIT_MSG" | grep -Eq "$PATTERN"; then
    echo "Commit message format is invalid. It should be '[PLM JIRA ID] | [JIRA Description] | [Commit Explanation with 25 characters at least]'."
    exit 1
fi