import { ZoneListPayload } from "src/app/bulk-process/preferences/preference.models";
import { AssignToteToOrderDto, BatchesRequest, BatchesResponse, OrderLineResource, OrderResponse, OrdersRequest, PartialToteIdRequest, PartialToteIdResponse, QuickPickOrdersRequest, RemoveOrderLinesRequest, RemoveOrderLinesResponse, TotesRequest, TotesResponse } from "../../Model/bulk-transactions";
import { ApiResult } from "../../types/CommonTypes";
import { Observable } from "rxjs";

export interface IBulkProcessApiService {
  bulkPickoOrderBatchToteQty(payload: any);
  bulkPickBatches(paylaod: BatchesRequest) : Observable<ApiResult<BatchesResponse[]>>;
  bulkPickBatchId(paylaod:any);
  bulkPickOrders(paylaod: OrdersRequest) : Observable<ApiResult<OrderResponse[]>>;
  bulkPickTotes(paylaod: TotesRequest) : Observable<ApiResult<TotesResponse[]>>;
  bulkPickOrdersQuickpick(paylaod: QuickPickOrdersRequest) : Observable<ApiResult<OrderResponse[]>>;
  bulkPickOrdersLocationAssignment(paylaod:any);
  bulkPickOrdersCheckLocationAssignment(paylaod:string[]);
  bulkPickOrdersCheckOffCarouselPicks(paylaod:string[]);
  GetOrdersMovedToReprocessAsync(paylaod:string[]);
  getOrderLinesAssignedLocations(paylaod:string[]);
  bulkPickZones();
  bulkPickBulkZone();
  addBulkPickBulkZone(payload:any);
  updateBulkPickBulkZone(payload:any);
  deleteBulkPickBulkZone(payload:any);
  deleteAllBulkPickBulkZone(payload:ZoneListPayload);
  addAllBulkPickBulkZone(payload:ZoneListPayload);
  bulkPreferences();
  validtote(body:any);
  BatchNextTote(numberOfIds: number);
  BatchesNextBatchID();
  BulkPickCreateBatch(body:any);
  updateLocationQuantity(body:any);
  bulkPickTaskComplete(body:any);
  fullTote(body:any);
  AssignToteToOrder(orders: AssignToteToOrderDto[]);
  updateOpenTransactionsZoneCaseQuantity(body: OrderLineResource[]);
  GetNextToteIdForSlapperLabelAsync(request: PartialToteIdRequest[]): Promise<PartialToteIdResponse[]>;
  SubmitCaseWiseOrders(request: PartialToteIdResponse[]): Promise<ApiResult<PartialToteIdResponse[]>>;
  RemoveOrderLinesFromTote(request: RemoveOrderLinesRequest): Promise<RemoveOrderLinesResponse>;
  bulkPickBatchesCount(payload:BatchesRequest) : Promise<ApiResult<number>>;
  bulkPickOrdersCount(payload:OrdersRequest) : Promise<ApiResult<number>>;
  bulkPickTotesCount(payload:TotesRequest) : Promise<ApiResult<number>>;
}
