export interface IInductionManagerApiService
{
  getPickBatchTransactionTable(payload : any);
   AllBatchDelete();    
   GetFromToteTypeAhead(); 
   SuperBatchIndex();
   NextBatchID();
   ProcessPutAwayIndex(); 
   NextTote(); 
   completeTransaction(payload : any);
   completePickBatch(payload : any);
   shortTransaction(payload : any);
   blossomTote(payload : any); 
   ClearPickToteInfo(payload : any);
   SelectBatchPickTA(payload : any);
   SelectToteTransManTable(payload : any);
   CompName();  
   PreferenceIndex();
   PickBatchFilterRename(payload : any);   
   ProcessBlossom(payload : any);   
   PickBatchZonesSelect(payload : any);
   PickBatchFilterTypeAhead(payload : any);
   PickBatchDefaultFilterMark(payload : any);
   PickBatchDefaultFilterClear(payload : any);
   PickBatchDefaultFilterSelect(payload : any);
   PickBatchFilterBatchDelete(payload : any);
   OrdersFilterZoneSelect(payload : any);
   PickToteTransDT(payload : any);
   PickBatchFilterOrderData(payload : any);
   PickBatchFilterUpdate(payload : any);
   PickBatchFilterInsert(payload : any);
   PickBatchOrderUpdate(payload : any);
   PickBatchOrderInsert(payload : any);
   PickBatchOrderDelete(payload : any);
   PickBatchZoneDefaultMark(payload : any);
   PickBatchFilterDelete(payload : any);
   OrdersInZone(payload : any);
   WSPickZoneSelect(payload : any);
   PickToteSetupIndex(payload : any);
   FillOrderNumber(payload : any);
   ValidateOrderNumber(payload : any);
   InZoneSetupProcess(payload : any);
   PickToteSetupProcess(payload : any);
   LocationZonesSelect(payload : any);
   WSPickZoneInsert(payload : any);
   WSPickZoneDelete(payload : any);
   ClrWSPickZone(); 
   InZoneTransDT(payload : any);
   TaskComplete(payload : any);  
   CrossDock(payload : any);
   FindLocation(payload : any);  
   CheckForwardLocations(payload : any);  
   IMUpdate(payload : any); 
   ItemDetails(payload : any);  
   AvailableZone(payload : any);  
   RPDetails(payload : any); 
   CompletePick(payload : any);  
   BatchLocationTypeAhead(payload : any) 
   ReserveLocation(payload : any);  
   BatchTotesDelete(payload : any);   
   TransTableView(payload : any);  
   TransactionForTote(payload : any);  
   NextSerialNumber(payload : any);
   ReelsCreate(payload : any);
   ValidateSn(payload : any);  
   BatchByZone(payload : any);    
   ItemZoneDataSelect(payload : any);
   SuperBatchCreate(payload : any);
   TotePrintTableInsert(payload : any);
   ReqDateDataSelect();  
   MarkToteFull(payload : any);
   CompleteBatch(payload : any);
   TotesTable(payload : any);
   BatchIDTypeAhead(payload : any);
   NextToteUpdate(payload : any);
   ProcessBatch(payload : any);
   ValidateTotesForPutAways(payload : any);
   BatchExist(payload : any);
   BatchTotes(payload : any);  
   ValidateTote(payload : any);
   ValidateItem(payload : any);
   ProcessPallet(payload : any);
   ValidateSerialNumber(payload : any);
   DeleteSerialNumber(payload : any);
   DynamicMethod(payload : any, url : string);
}